### PR TITLE
Cmake

### PR DESCRIPTION
**Pull request by VorpalBlade**
Things to do (that I will need some help with):
* Test the new build system on more than one computer
* Figure out the changes needed to CI (can't test sr.ht, they apparently require a paid plan? And Travis is apparently broken for this project)
* Test Arch build script.
* Update build documentation on wiki pages.

### CODE REVIEW

**Comment by FedeDP** [comment]
> Figure out the changes needed to CI (can't test sr.ht, they apparently require a paid plan? And Travis is apparently broken for this project)

Yeah, i'm switching to sr.ht for my CI as i really like the project. For now it is free though, but it will have a paid plan once it goes out of alpha.
Unfortunately i still could not get its github webhook to work with Clight and Clightd; i am investigating the issue (it seems a sr.ht side issue).

> Test Arch build script.

I will test it!

> Test the new build system on more than one computer

Obviously, i will test it :)

> Update build documentation on wiki pages.

This should be done by me i guess. Or i can make you a collaborator for this project, thus opening write permissions for gh wiki. That's up to you to choose :)

Btw I am not gonna test this today as I haven't got much time; will report back as soon as i test!

**Comment by VorpalBlade** [comment]
I made an attempt at fixing the sr.ht script. May or may not work.

**Review by FedeDP — CHANGES_REQUESTED** [review]
Can you split "build" from "prepare"? Have a look at https://github.com/FedeDP/libmodule/blob/master/.builds/archlinux.yml.
Possibly let's have 4 different "prepare + build" stages, ie: "prepare_debug/build_debug", "prepare_no_gamma/build_no_gamma" etc etc.

**Review by FedeDP — CHANGES_REQUESTED** [review]
It needs some small fixes, have a look here: https://github.com/FedeDP/libmodule/blob/master/Extra/Arch/PKGBUILD. 
Thanks!

**Comment by VorpalBlade** [comment]
It should indeed be possible to split out build from prepare, though perhaps it would be best to use different build directories then, instead of reusing the same one?

As for the PKGBUILD I'll attempt that yes.

**Comment by VorpalBlade** [comment]
Done, I'm not sure how the prepare_debug and so on would work, but assuming that sr.ht runs a bash-shell, what I did should work. I don't really feel inclined to learn details about sr.ht syntax since this would be the only project I used it for, and it won't be free after the alpha.

**Comment by VorpalBlade** [comment]
Another thing I only noticed just now is that you previously pulled the version from git instead of the cmake project version value. That could be arranged I believe, but what with all the focus on reproducible builds these days, I'm not sure that is such a good idea. It will also not work in any downloaded tar-ball releases files (obviously).

**Comment by VorpalBlade** [comment]
I noticed another difference: Handling of compiler flags, specifically the -Ofast and only enabling warning flags for debug builds. I don't really agree with either of those choices personally: warnings should always be enabled (perhaps with a switch to also turn on -Werror) but that should not be tied to Debug/Release.

However, it is your call in the end.

**Comment by FedeDP** [comment]
> It should indeed be possible to split out build from prepare, though perhaps it would be best to use different build directories then, instead of reusing the same one?
As for the PKGBUILD I'll attempt that yes.

I saw how you did it and it's great, thanks!

> I don't really feel inclined to learn details about sr.ht syntax since this would be the only project I used it for, and it won't be free after the alpha.

No problem sir :)

> Another thing I only noticed just now is that you previously pulled the version from git instead of the cmake project version value. That could be arranged I believe, but what with all the focus on reproducible builds these days, I'm not sure that is such a good idea. It will also not work in any downloaded tar-ball releases files (obviously).

Yup, that is a nice idea (to use CMAKE version macro)

> I noticed another difference: Handling of compiler flags, specifically the -Ofast and only enabling warning flags for debug builds. I don't really agree with either of those choices personally: warnings should always be enabled (perhaps with a switch to also turn on -Werror) but that should not be tied to Debug/Release.

Mmmh I always only enable debug flags for debug builds; I don't think end-user should see any warning while building (given that obviously no warning should be present ever).

Btw I had a look at the PR and it looks fine (and you are great at writing CMakeLists :D), thus i will probably merge it as soon as i got some time to eventually fix build/wiki pages/PKGBUILD; i'd say during weekend.

Thanks!

**Review by FedeDP — APPROVED** [review]

**Comment by VorpalBlade** [comment]
Just tried with -Wall -Wextra, and there is some stuff to do (at least for GCC, haven't tried clang).

**Comment by FedeDP** [comment]
I tested the patch and it works fine!
Just a small request: what about using CMAKE_INSTALL_LIBDIR and CMAKE_INSTALL_DATAROOTDIR here?
```
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/clightd.service
        DESTINATION /usr/lib/systemd/system)
install(FILES ${SCRIPT_DIR}/org.clightd.clightd.policy
        DESTINATION /usr/share/polkit-1/actions)
```

After this, i will gladly merge :)

EDIT: moreover, i'd use CMAKE_INSTALL_DOCDIR to install Clightd license to be more standard. I will then set  CMAKE_INSTALL_DOCDIR to /usr/share/licenses/ in PKGBUILD for Arch.

**Comment by VorpalBlade** [comment]
I don't think that systemd or policykit reads /opt/clight/share sadly. This means, that using the directories based on install prefix would break when install prefix is not /usr. For directories where I could find it, I used pkg-config to find out such install directories (such as the system bus directory). If you know a way to find the remaining directories that would be useful.

**Comment by FedeDP** [comment]
I see, thanks! It is fine then :)

**Comment by VorpalBlade** [comment]
I'll look into the DOCDIR thing tomorrow.

**Comment by FedeDP** [comment]
I noticed in Clight that an /usr/bin/clight-$VERSION is installed, and then linked to /usr/bin/clight.
I don't understand where this magic happens (and i'd like it to not happen :) ), can you point me?
Thanks!

**Comment by FedeDP** [comment]
I found it:
`set_target_properties(
    ${PROJECT_NAME} PROPERTIES
    VERSION ${PROJECT_VERSION}
    LINK_FLAGS "${COMBINED_LDFLAGS}"
)`

That VERSION field, as per doc: https://cmake.org/cmake/help/v3.0/command/set_target_properties.html.

**Pull request merged**
