### PR TITLE
Use CMAKE_INSTALL_* variables to install files

### PR DESCRIPTION
**Pull request by danyspin97**

### CODE REVIEW

**Comment by FedeDP** [comment]
Hi! Nice to see you back with another PR :)

Is this commit fixing any issue for you? Because that was a deliberate choice: we wanted to support installing clight in a non-standard location but in a standard environment; you can see my request here (same as your PR): https://github.com/FedeDP/Clightd/pull/15#issuecomment-441182010.

Thus, if this is just a cosmetic change, i'd say to keep current version.
Instead, if this is fixing a bug for you, we should find another way to solve the issue, ie: we can just use a -DOVERRIDDEN_LIB_DIR="/foo" -DOVERRIDDEN_DATA_DIR="/bar" that defaults to CMAKE_INSTALL_LIBDIR and CMAKE_INSTALL_DATAROOTDIR).

**Comment by danyspin97** [comment]
> Is this commit fixing any issue for you?

Yea, it is. I am packaging Clightd/Clight in Exherbo, which support multiple architectures by default. The package manager (paludis) use a different `PREFIX` based on the architecture, so my system is installed in `/usr/x86_64-pc-linux-gnu`. It also forbids the installation of files in `/usr/lib`, hence Clightd installation fails.

> we wanted to support installing clight in a non-standard location but in a standard environment

What do you mean? `CMAKE_INSTALL_LIBDIR` _is_ standard environment.

Some examples of `CMAKE_INSTALL_PREFIX`:

`CMAKE_INSTALL_PREFIX=/mnt/usr`, you're installing a software in system mounted in `/mnt`, assuming that there is a valid system in `/mnt` that use `/mnt/usr` as `PREFIX`.

`CMAKE_ISNTALL_PREFIX=/usr/x86_64-pc-linux-gnu`, the `PREFIX` used in my system. `CMAKE_INSTALL_LIBDIR` is `/usr/x86_64-pc-linux-gnu/lib` and `CMAKE_INSTALL_DATAROOTDIR` is `/usr/share`.

They are all standard environment afaik.

**Comment by FedeDP** [comment]
> CMAKE_INSTALL_PREFIX=/mnt/usr, you're installing a software in system mounted in /mnt, assuming that there is a valid system in /mnt that use /mnt/usr as PREFIX.

Yes, obviously. But the problem is: what happens if I have my system installed in root, thus using /usr, but i wish to install Clight in /opt?

**Comment by danyspin97** [comment]
> Yes, obviously. But the problem is: what happens if I have my system installed in root, thus using /usr, but i wish to install Clight in /opt?

Do you have a complete system in `/opt`? If yes, then you can install it without problems. If you don't, then you're using `CMAKE_INSTALL_LIBDIR` the wrong way.

**Comment by FedeDP** [comment]
> Do you have a complete system in /opt? If yes, then you can install it without problems. If you don't, then you're using CMAKE_INSTALL_LIBDIR the wrong way.

I agree with you that is an exceptional case; but you know there is no black/white here. Guy who contributed to Clightd CMake port (ie: he created the PR) had that need.  
I guess i won't merge a PR that breaks it unless he shows he's willing to patch Clightd CMakeLists all the time to suit his needs.
@VorpalBlade What do you think?

**Comment by danyspin97** [comment]
I can provide an ugly workaround for this but I'm against it. Something like a `SYSTEMD_LIB_DIR` variable that defaults to `CMAKE_INSTALL_LIB_DIR`.

I am also taking polkit actions directory from pkg-config.

**Comment by VorpalBlade** [comment]
I will not be able to look at this today, I live in a country celebrating Christmas on the 24th, not the 25th (Sweden). I'll try to figure out what this is about tomorrow.

**Comment by FedeDP** [comment]
Thanks both, and obviously merry Xmas everyone!! :)

**Comment by VorpalBlade** [comment]
Sorry for the late response.

The issue I see here is that it breaks when installing to a non-distro prefix, such as /usr/local, or /opt/something. It is recommended practice when installing something outside of your package manager to not install it directly to /usr.

In addition there doesn't seem to be a good way to dynamically find the systemd and polkit paths (using e.g. pkg-config). Some of the other paths can be found that way.

Nor does systemd or polkit seem to care about /usr/local versions of those paths from what I can tell, which seems to be a design flaw in those packages (contrast with e.g. python, which will add /usr/local/lib/python&lt;version&gt;/dist-packages to the search path on default installs).

An alternative could be to define two new configuration variables that default to  `${CMAKE_INSTALL_LIBDIR}/systemd/system` and `${CMAKE_INSTALL_DATADIR}/polkit-1/actions` respectively, but can then be overridden.

**Comment by FedeDP** [comment]
> An alternative could be to define two new configuration variables that default to ${CMAKE_INSTALL_LIBDIR}/systemd/system and ${CMAKE_INSTALL_DATADIR}/polkit-1/actions respectively, but can then be overridden.

This is what i first proposed. @DanySpin97 are you willing to take the job? 
Thanks both anyway!

**Comment by danyspin97** [comment]
> This is what i first proposed. @DanySpin97 are you willing to take the job?

Done. ^^

**Comment by FedeDP** [comment]
Mmh i don't understand your solution (that btw seems to only address `${CMAKE_INSTALL_LIBDIR}/systemd/system` path); i see a couple of things:
1) i prefer the approach pointed out above by @VorpalBlade 
2) We should fail if POLKIT_ACTION_DIR is empty/wrong (it is mandatory for Clightd). Or did i misunderstood `if(IS_DIRECTORY ${POLKIT_ACTION_DIR})` ?

Thus, i was thinking of something more like:
```
if (NOT SYSTEMD_SERVICE_DIR)  
    set(SYSTEMD_SERVICE_DIR ${CMAKE_INSTALL_LIBDIR}/systemd/system CACHE PATH
         "Systemd services directory")  
endif()
if (SYSTEMD_FOUND)
    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/clightd.service
         DESTINATION ${SYSTEMD_SERVICE_DIR})
endif()
```
Same for polkit.
This way it can be overridden by -DSYSTEMD_SERVICE_DIR=/foo/bar.

**Comment by danyspin97** [comment]
> We should fail if POLKIT_ACTION_DIR is empty/wrong

Ah, I see. Since there was no `pkg_check_module(REQUIRED polkit-gobject)` i thought that it wasn't required. I'll adjust accordingly.

> This way it can be overridden by -DSYSTEMD_SERVICE_DIR=/foo/bar

It is exactly the same. See [documentation](https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry).

**Comment by FedeDP** [comment]
> Ah, I see. Since there was no pkg_check_module(REQUIRED polkit-gobject) i thought that it wasn't required. I'll adjust accordingly.

You are righit; you can add that check! Note that it is a builddep only (just to retrieve that path through pkg-config).

> It is exactly the same. See documentation.

Thanks! Nice :) What about POLKIT_ACTION_DIR though?
Thank you very much!

**Comment by danyspin97** [comment]
> What about POLKIT_ACTION_DIR though?

If polkit is installed, actiondir should always contain a valid directory. You can check polkit version used by the various distro [here](https://repology.org/metapackage/polkit/versions) is always newer than 0.109, and version 0.109 already contained [actiondir](https://gitlab.freedesktop.org/polkit/polkit/blob/0.109/data/polkit-gobject-1.pc.in#L6).

I think it would be better to use pkg-config variable instead of letting the user override this value, since it points to the right directory, but I can put a variable as `SYSTEMD_SERVICE_DIR`.

**Comment by FedeDP** [comment]
@DanySpin97  Thank you very much for your support! This looks fine right now :)
Sorry if i made you waste some time...i'm pretty bad at cmake!

**Comment by danyspin97** [comment]
> @DanySpin97 Thank you very much for your support!

Thank you for this great piece of software :)

>  Sorry if i made you waste some time...i'm pretty bad at cmake!

It's okay ^^

**Comment by FedeDP** [comment]
Last thing: i see you removed:
```
# Use polkitd.service on ubuntu 16.04 (or wherever it is called polkitd instead of polkit)	
 find_file(POLKITD lib/systemd/system/polkitd.service)	
 if(POLKITD)	
     set(POLKIT_NAME "polkitd")	
 else()	
     set(POLKIT_NAME "polkit")	
 endif()
```
Is there a reason? :)

**Comment by danyspin97** [comment]
> Is there a reason? :)

Oops, sorry. I thought it was used in the polkit dir. Readded.

**Comment by FedeDP** [comment]
Doesn't `pkg_search_module(LOGIN_LIBS REQUIRED libelogind libsystemd>=221)` (L28) already define SYSTEMD_FOUND to true in case? ie: isn't L101 `pkg_check_modules(SYSTEMD libsystemd)` redundant?

**Comment by danyspin97** [comment]
>Doesn't pkg_search_module(LOGIN_LIBS REQUIRED libelogind libsystemd>=221) (L28) already define SYSTEMD_FOUND to true in case?

I asked myself the same thing but the [documentation](https://cmake.org/cmake/help/v3.13/module/FindPkgConfig.html#command:pkg_get_variable) doesn't specify so I guess it doesn't.

**Pull request merged**
